import type { Product } from "@/lib/types";

const productsData: Product[] = [
  {
    no: 1,
    description: "150GM ALUMINUM STANDUP POUCH WITH WINDOW & ZIPPER",
    size: { length: "200MM", width: "120MM", bottom: "80MM" },
    material: "PET/VMPET/PE 120μm",
    unit_price_birr: 32,
    slug: "150gm-aluminum-standup-pouch-with-window-and-zipper",
    category: "Aluminum Pouches",
    urls: [
      "https://i.ibb.co/sYPxS8w/image.png",
      "https://i.ibb.co/GQZYXwPF/image.png",
    ],
  },
  {
    no: 2,
    description: "250GM ALUMINUM STANDUP POUCH WITH WINDOW & ZIPPER",
    size: { length: "210MM", width: "140MM", bottom: "60MM" },
    material: "PET/VMPET/PE 120μm",
    unit_price_birr: 35,
    slug: "250gm-aluminum-standup-pouch-with-window-and-zipper",
    category: "Aluminum Pouches",
    urls: [
      "https://i.ibb.co/sYPxS8w/image.png",
      "https://i.ibb.co/GQZYXwPF/image.png",
    ],
  },
  {
    no: 3,
    description: "500GM (SMALL) ALUMINUM STANDUP POUCH WITH WINDOW & ZIPPER",
    size: { length: "240MM", width: "160MM", bottom: "80MM" },
    material: "PET/VMPET/PE 120μm",
    unit_price_birr: 40,
    slug: "500gm-small-aluminum-standup-pouch-with-window-and-zipper",
    category: "Aluminum Pouches",
    urls: [
      "https://i.ibb.co/sYPxS8w/image.png",
      "https://i.ibb.co/GQZYXwPF/image.png",
    ],
  },
  {
    no: 4,
    description: "500GM (BIG) ALUMINUM STANDUP POUCH WITH WINDOW & ZIPPER",
    size: { length: "270MM", width: "165MM", bottom: "90MM" },
    material: "PET/VMPET/PE 120μm",
    unit_price_birr: 45,
    slug: "500gm-big-aluminum-standup-pouch-with-window-and-zipper",
    category: "Aluminum Pouches",
    urls: [
      "https://i.ibb.co/sYPxS8w/image.png",
      "https://i.ibb.co/GQZYXwPF/image.png",
    ],
  },
  {
    no: 5,
    description: "1000GM ALUMINUM STANDUP POUCH WITH WINDOW & ZIPPER",
    size: { length: "300MM", width: "200MM", bottom: "100MM" },
    material: "PET/VMPET/PE 120μm",
    unit_price_birr: 50,
    slug: "1000gm-aluminum-standup-pouch-with-window-and-zipper",
    category: "Aluminum Pouches",
    urls: [
      "https://i.ibb.co/sYPxS8w/image.png",
      "https://i.ibb.co/GQZYXwPF/image.png",
    ],
  },
  {
    no: 6,
    description: "1500GM ALUMINUM STANDUP POUCH WITH WINDOW & ZIPPER",
    size: { length: "320MM", width: "220MM", bottom: "100MM" },
    material: "PET/VMPET/PE 120μm",
    unit_price_birr: 55,
    slug: "1500gm-aluminum-standup-pouch-with-window-and-zipper",
    category: "Aluminum Pouches",
    urls: [
      "https://i.ibb.co/sYPxS8w/image.png",
      "https://i.ibb.co/GQZYXwPF/image.png",
    ],
  },
  {
    no: 7,
    description: "250GM KRAFT PAPER STANDUP POUCH WITH WINDOW & ZIPPER",
    size: { length: "210MM", width: "140MM", bottom: "60MM" },
    material: "MOPP/PAPER/PE 155μm",
    unit_price_birr: 36.5,
    slug: "250gm-kraft-paper-standup-pouch-with-window-and-zipper",
    category: "Kraft Paper Pouches",
    urls: [
      "https://i.ibb.co/5gqtNT5j/image.png",
      "https://i.ibb.co/chrCLK4h/image.png",
    ],
  },
  {
    no: 8,
    description: "500GM KRAFT PAPER STANDUP POUCH WITH WINDOW & ZIPPER",
    size: { length: "240MM", width: "160MM", bottom: "80MM" },
    material: "MOPP/PAPER/PE 155μm",
    unit_price_birr: 43,
    slug: "500gm-kraft-paper-standup-pouch-with-window-and-zipper",
    category: "Kraft Paper Pouches",
    urls: [
      "https://i.ibb.co/5gqtNT5j/image.png",
      "https://i.ibb.co/chrCLK4h/image.png",
    ],
  },
  {
    no: 9,
    description: "1000GM KRAFT PAPER STANDUP POUCH WITH WINDOW & ZIPPER",
    size: { length: "300MM", width: "190MM", bottom: "90MM" },
    material: "MOPP/PAPER/PE 155μm",
    unit_price_birr: 54,
    slug: "1000gm-kraft-paper-standup-pouch-with-window-and-zipper",
    category: "Kraft Paper Pouches",
    urls: [
      "https://i.ibb.co/5gqtNT5j/image.png",
      "https://i.ibb.co/chrCLK4h/image.png",
    ],
  },
  {
    no: 10,
    description: "1000GM COFFEE QUADRILATERAL SEALED POUCH",
    size: { length: "410MM", width: "130MM", side: "(70+70)MM" },
    material: "MOPP/VMPET/PE 150μm",
    unit_price_birr: 42,
    slug: "1000gm-coffee-quadrilateral-sealed-pouch",
    category: "Coffee Pouches",
    urls: ["https://i.ibb.co/XZ1gvH1D/image.png"],
  },
  {
    no: 11,
    description: "250GM COFFEE 3D POUCH WITH ZIPPER & VALVE",
    size: { length: "220MM", width: "125MM", side: "(70+70)MM" },
    material: "MOPP/VMPET/PE 130μm",
    unit_price_birr: 46,
    slug: "250gm-coffee-3d-pouch-with-zipper-and-valve",
    category: "Coffee Pouches",
    urls: ["https://i.ibb.co/BV58Dhww/image.png"],
  },
  {
    no: 12,
    description: "500GM COFFEE 3D POUCH WITH ZIPPER & VALVE",
    size: { length: "260MM", width: "130MM", side: "(90+90)MM" },
    material: "MOPP/VMPET/PE 130μm",
    unit_price_birr: 54,
    slug: "500gm-coffee-3d-pouch-with-zipper-and-valve",
    category: "Coffee Pouches",
    urls: ["https://i.ibb.co/BV58Dhww/image.png"],
  },
  {
    no: 13,
    description: "1KG COFFEE 3D POUCH WITH ZIPPER & VALVE",
    size: { length: "300MM", width: "145MM", side: "(100+100)MM" },
    material: "MOPP/VMPET/PE 130μm",
    unit_price_birr: 64,
    slug: "1kg-coffee-3d-pouch-with-zipper-and-valve",
    category: "Coffee Pouches",
    urls: ["https://i.ibb.co/BV58Dhww/image.png"],
  },
  {
    no: 14,
    description: "TRANSPARENT STANDUP POUCH WITH ZIPPER",
    size: { length: "210MM", width: "140MM", bottom: "60MM" },
    material: "PET/VMPET/PE 120μm",
    unit_price_birr: 34,
    slug: "transparent-standup-pouch-with-zipper-210x140x60",
    category: "Transparent Pouches",
    urls: ["https://i.ibb.co/5WWpTMpL/image.png"],
  },
  {
    no: 15,
    description: "TRANSPARENT STANDUP POUCH WITH ZIPPER",
    size: { length: "270MM", width: "165MM", bottom: "90MM" },
    material: "PET/VMPET/PE 120μm",
    unit_price_birr: 39,
    slug: "transparent-standup-pouch-with-zipper-270x165x90",
    category: "Transparent Pouches",
    urls: ["https://i.ibb.co/5WWpTMpL/image.png"],
  },
  {
    no: 16,
    description: "TRANSPARENT STANDUP POUCH WITH ZIPPER",
    size: { length: "320MM", width: "220MM", bottom: "100MM" },
    material: "PET/VMPET/PE 120μm",
    unit_price_birr: 49,
    slug: "transparent-standup-pouch-with-zipper-320x220x100",
    category: "Transparent Pouches",
    urls: ["https://i.ibb.co/5WWpTMpL/image.png"],
  },
  // Coffee cups
  {
    no: 17,
    description: "COFFEE CUP 12OZ",
    size: { length: "12OZ", width: "12OZ" },
    material: "Paper cup",
    unit_price_birr: 15,
    slug: "coffee-cup-12oz-15-birr",
    category: "Coffee Cups",
    urls: ["https://i.ibb.co/mVrbp7Fr/image.png"],
  },
  {
    no: 18,
    description: "COFFEE CUP 12OZ",
    size: { length: "12OZ", width: "12OZ" },
    material: "Paper cup",
    unit_price_birr: 18,
    slug: "coffee-cup-12oz-18-birr",
    category: "Coffee Cups",
    urls: ["https://i.ibb.co/9HvyQf50/image.png"],
  },
  {
    no: 19,
    description: "COFFEE CUP 8OZ",
    size: { length: "8OZ", width: "8OZ" },
    material: "Paper cup",
    unit_price_birr: 15,
    slug: "coffee-cup-8oz-15-birr",
    category: "Coffee Cups",
    urls: ["https://i.ibb.co/rnNBK6t/image.png"],
  },
];

export default productsData;
